### PR TITLE
Adapt Permissions and add ServerMessage

### PR DESCRIPTION
**Pull request by urmet0**
I adapted the permissions to the current working format.
Also it is possible now to add commands for each user.
Additionally there is a parameter for ServerMessage.

Maybe you would like to merge this into original repo.

### CODE REVIEW

**Comment by gnoeley** [comment]
Thanks for adding this. I haven't started the server in a while so I'll try and take a quick look this week and get this merged! Looks alright from a cusrosry glance, even fixed my exsitning typos, nice 👍

**Comment by urmet0** [comment]
Hey, I also had to adapt the Dockerfile to get it built. The wget install had to get all this additional stuff removed.
apt-get install -y --no-install-recommends --no-install-suggests wget=1.20.1-1.1 ca-certificates=20190110
to
apt-get install -y wget

This way the build worked for me. I think I should create a pull request for the dockerfile too, because also the defaults for the ServerMessage is set in there. Currently this is missing in that pull-request.

**Comment by urmet0** [comment]
I added 1 more commit for the Dockerfile changes and additionally there are these params BAR_START_WHEN_CLIENTS_READY and BAR_START_WHEN_CLIENTS_READY_RATIO added.

**Comment by Zimomo333** [comment]
> I adapted the permissions to the current working format. Also it is possible now to add commands for each user. Additionally there is a parameter for ServerMessage.
> 
> Maybe you would like to merge this into original repo.

It works well, thanks! @urmet0
I have a suggestion for entry.sh
 --env BAR_PERMISSIONS=InGameUsername1:Steam64ID1:Perm1,Perm2:Command1,Command2;

when the Command is not set as follow, clientpermissions.xml will be lack of clientend=">". Maybe you can be compatible with this situation.
--env BAR_PERMISSIONS=InGameUsername1:Steam64ID1:Perm1,Perm2:;

 @gnoeley I think urmet's pr is acceptable.

**Comment by gnoeley** [comment]
Thanks for taking a look at this @Zimomo333 . I just checked and can confirm, when _not_ including the optional `<Command>` entries, the server fails to start with 
> Couldn't load xml document "Data/clientpermissions.xml"! {Name cannot begin with the '<' character, hexadecimal value 0x3C. Line 8, position 5.}

I'll push a fix for this then get this merged :+1: 

And thanks again @urmet0 for updating for the new version of the game, sorry it's take me so long to merge!

**Comment by gnoeley** [comment]
Fixed this issue in https://github.com/gnoeley/barotrauma-dedicated-server-docker/commit/c8f9fca7995ccbc0e89b210a098b48d80ccd9ac8

Also, if you could quickly check the updated README.md make sense that would be much appreciated :pray:

**Pull request merged**
